apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avocado-production-redis-pvc
  labels:
    username: phart
    env: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
