apiVersion: v1
kind: Service
metadata:
  name: avocado-production-redis-service
  labels:
    username: phart
    env: production
spec:
  type: ClusterIP
  selector:
    app: avocado-production-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
