version: "3"

services:
  api:
    image: avocado/api:latest
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
  worker:
    image: avocado/worker:latest
    depends_on:
      - "redis"
      - "postgres"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: avocado
      POSTGRES_PASSWORD: avocado
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/avocado.csv:/avocado.csv
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
  redis:
    build: redis
    restart: always
    ports:
      - "6379:6379"

