---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avocado-test-worker-deployment
  labels:
    app: avocado-test-worker
    username: phart
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avocado-test-worker
  template:
    metadata:
      labels:
        app: avocado-test-worker
        username: phart
        env: test
    spec:
      containers:
        - name: avocado-test-worker-container
          imagePullPolicy: Always
          image: phart26/avocado-test-wrk:latest
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: "PG_HOST"
              value: "10.100.120.60"
            - name: "PG_USER"
              value: "jmmpahcoe"
            - name: "PG_PASSWORD"
              value: "avocado"
            - name: "PG_DATABASE"
              value: "postgesdb"
            - name: "REDIS_HOST"
              value: "10.110.128.5"
